//*********************************************************/
//*  Script for carbon-calculator                         */
//*  Version: 0.11                                       */
//*  Authored by Mark Stout                               */
//*  Copyright 2021 Mark Stout, All rights reserved       */
//*  Distributed under the GNU License                    */
//*********************************************************/

// This function converts electric and natural gas.
function calculateCO2e() {
	// conversion variables
	tonne  = 2000;         	// lbs per ton
	mill   = 1000000;	   	// One million
	iBTU   = 100000;       	// BTUs in a Therm
	aRate  = 0.00015246;   	// lbs per 1 BTU burning aviation fuel
	cRate  = 0.00021106;   	// lbs per 1 BTU burning coal
	gRate  = 0.185;        	// CO2 generated by burning natural gas is 0.185 (kg/kWh)
	hRate  = 0.00016555;   	// lbs per 1 BTU heating fuel
	jRate  = 0.00015925;   	// lbs per 1 BTU burning jet fuel
	kRate  = 0.85;		   	// lbs CO per kWh averaged
	lRate  = 2.20462;      	// lbs per kg;
	nRate  = 0.00011665;   	// lbs per 1 BTU burning natural gas 
	pRate  = 0.00013863;   	// lbs per 1 BTU burning propane gas
	tRate  = 29.3;         	// kWh per Therm from natural gas;
	xRate  = 0.23114;      	// kg CO2e per kWh;

	arrRates = {};
		arrRates["a"] = aRate;
		arrRates["c"] = cRate;
		arrRates["h"] = hRate;
		arrRates["j"] = jRate;
		arrRates["n"] = nRate;
		arrRates["p"] = pRate;

	arrFuelType = {};
		arrFuelType["a"] = "Aviation Fuel";
		arrFuelType["c"] = "Coal (all types)";
		arrFuelType["h"] = "Heating Oil";
		arrFuelType["j"] = "Jet Fuel";
		arrFuelType["n"] = "Natural Gas";
		arrFuelType["p"] = "Propane";

		
	// grab form field values
	tName = document.getElementById("your-name").value;
	tCompany = document.getElementById("company-name").value;
	tIndustry = document.getElementById("industry").value;
	tEmail = document.getElementById("email").value;
	tPhone = document.getElementById("phone").value;
	tZipcode = document.getElementById("zipcode").value;
	tCountry = document.getElementById("country").value;

	tkWh=document.getElementById("kWh").value;
	ikWh = parseInt(tkWh);
	tFuel=document.getElementById("fuel-type").value;
       fUsed=document.getElementById("fuel-used").value;
       fRate = arrRates[tFuel.substring(0,1)];

	// CO² emitted per kWh in lbs 
	co2ekWh = (ikWh * kRate) / tonne; 
	if(co2ekWh >= 1) {
		co2ekWh = co2ekWh.toFixed(2);
	} else {
		co2ekWh = co2ekWh.toFixed(4);		
	}

	// CO² emitted per fuel type used in lbs
	co2eFuel = (fUsed * fRate) / tonne;
	if(co2eFuel >= 1) {
		co2eFuel = co2eFuel.toFixed(0);
	} else {
		co2eFuel = co2eFuel.toFixed(4);		
	}

	totalCO2e = Number(co2ekWh) + Number(co2eFuel);
	if(totalCO2e >= 1) {
		totalCO2e = totalCO2e.toFixed(0);
	} else {
		totalCO2e = totalCO2e.toFixed(2);		
	}


	//Display results
	txtResponse = "<p>" + tName + ", your company, " + tCompany + ", is emitting " + totalCO2e + "</b> tons of CO² annually.</p>  <p>By hiring Apollo Energies, " + tCompany + " can reduce their carbon emissions by <b>" + (totalCO2e * 0.3).toFixed(0) + "</b> tons of CO². </p><p>With help from Apollo Energies, " + tCompany + " can become carbon-free and reduce the remaining tons of <b>" + (totalCO2e * 0.7).toFixed(0) + "</b> CO² emissions.  This is a significant amount.</p><p>There was <b>" + co2ekWh + "</b> tons of CO² emitted from electricity used and <b>" + co2eFuel + "</b> tons of CO² emitted burning of " + arrFuelType[tFuel.substring(0,1)] + ".</p> <p>Bringing the total CO² emissions for " + tCompany + " to <b>" + totalCO2e + "</b> tons of CO².</p><p>Let us help you remove <b>" + totalCO2e + "</b> tons of CO²!<p>&nbsp;</p><button class=\"myButtons\" onclick=\"location.href='https://calendly.com/mark-stout/'\" >Schedule a brief meeting!</button>";

	// Sets the title of the report
	showResultsTitle = "Carbon Emissions<br>for<br>" + tCompany;

	// hides the form 
    document.getElementById("container").style.display = 'none';

    // populates the HTML inside the <p> tag
	document.getElementById("showResultsTitle").innerHTML = showResultsTitle;
	document.getElementById("showResultsResponse").innerHTML = txtResponse;

	// diplays the DIV with the populated HTML in <p> tag 
	document.getElementById("showResultsDiv").style.display = "block";

	
}


function myAlerts(message) {
	alert(message)
}


function refreshPage() {
	if(confirm("Are you sure, want to refresh?")) {
	 	location.reload(); 
	}
}